### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xca in position 1694: invalid continuation byte

### ISSUE THREAD

**Issue by alphafox02** [azmatt/chasing_your_tail#3]
After adapting paths to my current Pi setup w/ Kismet I can run chasing your tail and retrieve wifi results, however, after about 15 minutes running this happened. 

Traceback (most recent call last):
  File "/home/ubuntu/chasing_your_tail/cyt/chasing_your_tail.py", line 204, in <module>
    probe_request_sql_fetch_past_5(con)
  File "/home/ubuntu/chasing_your_tail/cyt/chasing_your_tail.py", line 192, in probe_request_sql_fetch_past_5
    raw_device_json = json.loads(row[2])
  File "/usr/lib/python3.8/json/__init__.py", line 343, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xca in position 1694: invalid continuation byte
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 32, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 12, in <module>
    import os, glob, subprocess, os.path, time, pwd, sys, requests_unixsocket
ModuleNotFoundError: No module named 'requests_unixsocket'

Unix socket is installed with pip3, but I'll try and update it. It appears thought that maybe there's an issue decoding something.?

**Comment by alphafox02** [comment]
Deleting the kismet logs and starting over allows the chasing your tail program to run, so I assume it's something with the sql database and captured wifi devices it doesn't like.

**Comment by alphafox02** [comment]
Latest kismet nightly addressed and resolved this issue for me.
